stages:
- build
- test
- deploy 

image: registry.gitlab.com/nebulrgroup/nebulr-build-containers:latest
before_script:
  - export GITLAB_NPM_REPOSITORY_TOKEN="${CI_JOB_TOKEN}"
  - ./init.sh

build:
  stage: build
  script:    
    - npm run build
  except:
    refs:
      - master
      - stage

code coverage:
  stage: test
  script:    
    - npm run test:cov
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  except:
    refs:
      - master
      - stage

lint:
  stage: test
  script:    
    - npm run lint
  except:
    refs:
      - master
      - stage

test:
  stage: test
  script:  
    - npm run test
  except:
    refs:
      - master
      - stage

publish package:
  stage: deploy
  script:
    - npm publish
  only:
    refs:
      - master